"""Value ranges and missingness, measured per site and channel (M1a step 8).

Two tracked reports, each generated from the staged data by one command:

* ``faultline inspect ranges`` reads every *ingested* value, before any bound, and gives
  per source and channel the percentiles from p0.01 to p99.99, the values that repeat in
  the extreme tails (a sentinel shows up as one exact value, many times), and what a
  configuration's sentinel list and bounds remove. It is the evidence behind the bounds
  in ``telemetry_v2.yaml``.
* ``faultline inspect missingness`` reads the *cleaned* grid and the *final* tables and
  answers the questions serialization, context length and model size are chosen from:
  per site and core channel, the non-null share before and after imputation and the
  imputed share; the length of the gaps; how many core channels are present in the same
  10-minute step; and, at the held-out site, each core channel per year -- wind direction
  is core but absent from the 2019 export.

Every figure is accumulated turbine-year by turbine-year, so memory stays at one file.
"""

from __future__ import annotations

from collections import Counter
from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd

from faultline.data.common.report import kv_table, section, table
from faultline.data.telemetry.clean import SENTINEL_TOLERANCE
from faultline.data.telemetry.pipeline import (
    TelemetryPipelineConfig,
    ingest_dir,
    parquet_files,
    stage_source_dir,
)
from faultline.data.telemetry.schemas import IMPUTED_SUFFIX
from faultline.logging_utils import get_logger
from faultline.paths import ProjectPaths
from faultline.runs import git_sha

logger = get_logger(__name__)

#: Quantiles of the ranges report.
QUANTILES: tuple[float, ...] = (0.0001, 0.001, 0.01, 0.5, 0.99, 0.999, 0.9999)

#: Gap-length buckets, in steps: (lowest, highest, label).
GAP_BUCKETS: tuple[tuple[int, int, str], ...] = (
    (1, 1, "1 step"),
    (2, 3, "2-3"),
    (4, 5, "4-5"),
    (6, 35, "6-35 (to 6 h)"),
    (36, 143, "36-143 (to 1 day)"),
    (144, 1007, "144-1007 (to 1 week)"),
    (1008, 10**9, ">= 1 week"),
)


def _stamp() -> str:
    return datetime.now(tz=UTC).strftime("%Y%m%d")


def _header(title: str, config_path: Path, repo_root: Path, command: str) -> str:
    return f"# {title}\n\n" + kv_table(
        {
            "config": config_path.as_posix(),
            "generated (UTC)": datetime.now(tz=UTC).isoformat(timespec="seconds"),
            "git_sha": git_sha(repo_root),
            "generated by": command,
        }
    )


# -------------------------------------------------------------------------------------
# ranges
# -------------------------------------------------------------------------------------


def ranges_rows(
    values: pd.Series, bounds: tuple[float, float] | None, codes: Sequence[float]
) -> dict[str, object]:
    """Describe one channel's values at one source.

    Args:
        values: Every ingested value, nulls included.
        bounds: The configured ``(min, max)``, if any.
        codes: The configured sentinel values.

    Returns:
        Count, quantiles, the repeated tail values, sentinel hits and out-of-bound count.
    """
    numeric = pd.to_numeric(values, errors="coerce").dropna()
    if numeric.empty:
        return {"n": 0}
    q = numeric.quantile(list(QUANTILES)).to_numpy()
    low, high = numeric.quantile(0.001), numeric.quantile(0.999)
    tails = pd.concat([numeric[numeric <= low], numeric[numeric >= high]]).round(2)
    repeated = tails.value_counts()
    repeated = repeated[repeated >= 10].head(4)
    hit = np.zeros(len(numeric), dtype=bool)
    for code in codes:
        hit |= np.isclose(numeric.to_numpy(dtype=float), code, rtol=0.0, atol=SENTINEL_TOLERANCE)
    kept = numeric[~hit]
    outside = int(((kept < bounds[0]) | (kept > bounds[1])).sum()) if bounds is not None else 0
    return {
        "n": int(len(numeric)),
        "min": float(numeric.min()),
        **{f"p{x * 100:g}": float(v) for x, v in zip(QUANTILES, q, strict=True)},
        "max": float(numeric.max()),
        "repeated tail values": ", ".join(f"{k:g} x{v:,}" for k, v in repeated.items()) or "-",
        "sentinel values removed": int(hit.sum()),
        "outside bounds": outside,
    }


def inspect_ranges(
    paths: ProjectPaths, config: TelemetryPipelineConfig, config_path: Path, sources: Sequence[str]
) -> Path:
    """Write the ranges report for the given sources.

    Args:
        paths: Resolved project paths.
        config: The configuration whose sentinels and bounds are applied.
        config_path: Where it was read from.
        sources: Sources to measure.

    Returns:
        The report path.
    """
    parts = [
        _header(
            "Value ranges before any bound",
            config_path,
            paths.repo_root,
            "faultline inspect ranges",
        ),
        "\nEvery ingested value, before sentinels and bounds. `repeated tail values` lists "
        "values at or beyond p0.1 and p99.9 that occur at least 10 times: a sentinel shows "
        "up there as one exact value, many times. The last two columns are what the "
        "configuration's sentinel list and bounds remove.\n",
    ]
    for source in sources:
        files = parquet_files(ingest_dir(paths, source))
        if not files:
            continue
        frame = pd.concat([pd.read_parquet(p) for p in files], ignore_index=True, sort=False)
        bounds = config.bounds_for(source)
        codes = config.clean.sentinels.get(source, {})
        rows: list[tuple[object, ...]] = []
        for channel in config.channels:
            if channel not in frame.columns:
                rows.append((channel, "absent", *[""] * 13))
                continue
            spec = bounds.get(channel)
            described = ranges_rows(
                frame[channel],
                (spec.min, spec.max) if spec is not None else None,
                codes.get(channel, []),
            )
            if described["n"] == 0:
                rows.append((channel, 0, *[""] * 13))
                continue
            rows.append(
                (
                    channel,
                    described["n"],
                    described["min"],
                    *(described[f"p{x * 100:g}"] for x in QUANTILES),
                    described["max"],
                    f"[{spec.min:g}, {spec.max:g}]" if spec is not None else "-",
                    described["repeated tail values"],
                    described["sentinel values removed"],
                    described["outside bounds"],
                )
            )
        parts.append(
            section(
                f"{source} ({len(frame):,} rows)",
                table(
                    [
                        "channel",
                        "n",
                        "min",
                        *(f"p{x * 100:g}" for x in QUANTILES),
                        "max",
                        "bounds",
                        "repeated tail values",
                        "sentinels removed",
                        "outside bounds",
                    ],
                    rows,
                ),
            )
        )
    destination = paths.data_reports_dir / f"ranges_{_stamp()}.md"
    destination.write_text("".join(parts), encoding="utf-8")
    logger.info("wrote %s", destination)
    return destination


# -------------------------------------------------------------------------------------
# missingness
# -------------------------------------------------------------------------------------


def gap_runs(missing: np.ndarray) -> np.ndarray:
    """Lengths of the runs of ``True`` in a boolean array.

    Args:
        missing: ``True`` where a value is missing.

    Returns:
        The length of every run, in order.
    """
    if missing.size == 0:
        return np.zeros(0, dtype=np.int64)
    padded = np.r_[False, missing, False].astype(np.int8)
    edges = np.flatnonzero(np.diff(padded))
    return (edges[1::2] - edges[0::2]).astype(np.int64)


@dataclass
class ChannelTally:
    """One channel's missingness at one site."""

    grid_steps: int = 0
    grid_present: int = 0
    final_rows: int = 0
    final_before: int = 0
    final_after: int = 0
    imputed: int = 0
    gaps: Counter[int] = field(default_factory=Counter)


@dataclass
class SiteTally:
    """One site's missingness."""

    channels: dict[str, ChannelTally] = field(default_factory=dict)
    presence_grid: Counter[int] = field(default_factory=Counter)
    presence_final: Counter[int] = field(default_factory=Counter)
    grid_steps: int = 0
    final_rows: int = 0
    by_year: dict[int, dict[str, list[int]]] = field(default_factory=dict)


def tally_grid(frame: pd.DataFrame, core: Sequence[str], site: SiteTally) -> None:
    """Accumulate one cleaned turbine-year: coverage, gaps, presence per step, per year."""
    site.grid_steps += len(frame)
    present = np.zeros(len(frame), dtype=np.int64)
    years = pd.to_datetime(frame["timestamp_utc"], utc=True).dt.year.to_numpy()
    for channel in core:
        tally = site.channels.setdefault(channel, ChannelTally())
        tally.grid_steps += len(frame)
        values = (
            frame[channel] if channel in frame.columns else pd.Series(np.nan, index=frame.index)
        )
        notna = values.notna().to_numpy()
        tally.grid_present += int(notna.sum())
        tally.gaps.update(gap_runs(~notna).tolist())
        present += notna
        for year in np.unique(years):
            here = years == year
            counts = site.by_year.setdefault(int(year), {}).setdefault(channel, [0, 0])
            counts[0] += int(here.sum())
            counts[1] += int((notna & here).sum())
    site.presence_grid.update(
        {k: int(v) for k, v in enumerate(np.bincount(present, minlength=len(core) + 1))}
    )


def tally_final(frame: pd.DataFrame, core: Sequence[str], site: SiteTally) -> None:
    """Accumulate one final turbine-year: coverage before and after imputation."""
    site.final_rows += len(frame)
    present = np.zeros(len(frame), dtype=np.int64)
    for channel in core:
        tally = site.channels.setdefault(channel, ChannelTally())
        tally.final_rows += len(frame)
        if channel not in frame.columns:
            continue
        notna = frame[channel].notna().to_numpy()
        mask = f"{channel}{IMPUTED_SUFFIX}"
        imputed = (
            frame[mask].fillna(False).to_numpy(dtype=bool)
            if mask in frame.columns
            else np.zeros(len(frame), dtype=bool)
        )
        tally.final_after += int(notna.sum())
        tally.final_before += int((notna & ~imputed).sum())
        tally.imputed += int(imputed.sum())
        present += notna
    site.presence_final.update(
        {k: int(v) for k, v in enumerate(np.bincount(present, minlength=len(core) + 1))}
    )


def _share(part: int, whole: int, digits: int = 1) -> str:
    return f"{part / whole * 100:.{digits}f}%" if whole else "n/a"


def render_missingness(
    sites: dict[str, SiteTally], core: Sequence[str], header: str, held_out: str | None
) -> str:
    """Render the missingness report.

    Args:
        sites: The tallies per source.
        core: Core channels, in canonical order.
        header: The report header.
        held_out: The held-out source, whose per-year table is printed.

    Returns:
        A Markdown document.
    """
    parts = [
        header,
        "\n`clean grid` is every step of the cleaned grid, gaps included, after sentinels and "
        "bounds. `final` is the rows that survive filtering -- segments of at least a day, a "
        "long gap ending one -- with short gaps imputed and flagged. `before` counts measured "
        "values, `after` measured plus imputed. A channel a site does not publish reads 0%.\n",
    ]
    rows = []
    for source, site in sites.items():
        for channel in core:
            t = site.channels.get(channel, ChannelTally())
            rows.append(
                (
                    source,
                    channel,
                    _share(t.grid_present, t.grid_steps),
                    _share(t.final_before, t.final_rows),
                    _share(t.final_after, t.final_rows),
                    _share(t.imputed, t.final_rows, digits=3),
                )
            )
    parts.append(
        section(
            "Non-null share per site and core channel, before and after imputation",
            table(
                [
                    "site",
                    "channel",
                    "clean grid",
                    "final, before imputation",
                    "final, after imputation",
                    "imputed steps",
                ],
                rows,
            ),
        )
    )
    gap_rows = []
    for source, site in sites.items():
        for channel in core:
            gaps = site.channels.get(channel, ChannelTally()).gaps
            missing = sum(length * n for length, n in gaps.items())
            lengths = np.repeat(np.array(list(gaps), dtype=np.int64), list(gaps.values()))
            buckets = [
                _share(sum(length * n for length, n in gaps.items() if lo <= length <= hi), missing)
                for lo, hi, _ in GAP_BUCKETS
            ]
            gap_rows.append(
                (
                    source,
                    channel,
                    int(sum(gaps.values())),
                    missing,
                    int(np.median(lengths)) if lengths.size else 0,
                    int(np.percentile(lengths, 90)) if lengths.size else 0,
                    int(lengths.max()) if lengths.size else 0,
                    *buckets,
                )
            )
    parts.append(
        section(
            "Gap lengths on the clean grid",
            "A gap is a run of consecutive missing steps within one turbine-year. The bucket "
            "columns give the share of the missing steps that lie in gaps of that length. "
            "Short gaps (up to `max_impute_steps`) are imputed; a gap of `segment_break_steps` "
            "or more ends a segment.\n\n"
            + table(
                [
                    "site",
                    "channel",
                    "gaps",
                    "missing steps",
                    "median length",
                    "p90 length",
                    "longest",
                    *(label for _, _, label in GAP_BUCKETS),
                ],
                gap_rows,
            ),
        )
    )
    width = len(core) + 1
    presence_rows = []
    for source, site in sites.items():
        for name, counts, total in (
            ("clean grid", site.presence_grid, site.grid_steps),
            ("final, after imputation", site.presence_final, site.final_rows),
        ):
            presence_rows.append(
                (source, name, *(_share(counts.get(k, 0), total) for k in range(width)))
            )
    parts.append(
        section(
            "Core channels present in the same 10-minute step",
            f"Share of steps with exactly k of the {len(core)} core channels non-null.\n\n"
            + table(["site", "rows", *(str(k) for k in range(width))], presence_rows),
        )
    )
    if held_out and held_out in sites:
        site = sites[held_out]
        # Years with at least a day of grid: moving interval-end labels to interval start
        # leaves one-row files in the year before each staged year.
        years = sorted(
            y for y, counts in site.by_year.items() if counts.get(core[0], [0, 0])[0] >= 144
        )
        total = sum(counts.get(core[0], [0, 0])[0] for counts in site.by_year.values())
        body = kv_table(
            {
                f"{year} share of the held-out grid": _share(
                    site.by_year[year].get(core[0], [0, 0])[0], total
                )
                for year in years
            }
        )
        body += "\n" + table(
            ["channel", *(str(y) for y in years)],
            [
                (
                    channel,
                    *(
                        _share(
                            site.by_year[y].get(channel, [0, 0])[1],
                            site.by_year[y].get(channel, [0, 0])[0],
                        )
                        for y in years
                    ),
                )
                for channel in core
            ],
        )
        parts.append(
            section(
                f"{held_out}: each core channel per year (clean grid)",
                "Wind direction is core -- the provider's lookup describes it and the 2023 "
                "export carries it -- but the 2019 export does not. Whatever the model reads "
                "at the held-out site, it reads without wind direction in one of its two "
                "years.\n\n" + body,
            )
        )
    return "".join(parts)


def inspect_missingness(
    paths: ProjectPaths,
    config: TelemetryPipelineConfig,
    config_path: Path,
    sources: Sequence[str],
    held_out: str | None = "hill_of_towie",
) -> Path:
    """Write the missingness report from the cleaned and final tables.

    Args:
        paths: Resolved project paths.
        config: The configuration the tables were produced under.
        config_path: Where it was read from.
        sources: Sources to measure.
        held_out: The held-out source, whose per-year table is printed.

    Returns:
        The report path.
    """
    core = list(config.core_channels) or list(config.channels)
    sites: dict[str, SiteTally] = {}
    for source in sources:
        site = SiteTally()
        for path in parquet_files(stage_source_dir(paths, "cleaned", source)):
            tally_grid(pd.read_parquet(path), core, site)
        for path in parquet_files(stage_source_dir(paths, "final", source)):
            tally_final(pd.read_parquet(path), core, site)
        if site.grid_steps:
            sites[source] = site
    header = _header(
        "Missingness per site and core channel",
        config_path,
        paths.repo_root,
        "faultline inspect missingness",
    )
    destination = paths.data_reports_dir / f"missingness_{_stamp()}.md"
    destination.write_text(render_missingness(sites, core, header, held_out), encoding="utf-8")
    logger.info("wrote %s", destination)
    return destination
